lsi: false
safe: true
incremental: false
highlighter: rouge
gist:
  noscript: false
plugins:
  - jekyll-target-blank
theme: jekyll-theme-cayman
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

# Mixpanel Integration
mixpanel_token: 2e7c9cfd6965f217ac48a6427b824e2f